# ???? ??
spring.application.name=StartProject

# MariaDB
spring.datasource.url=jdbc:mariadb://aws2020.cleao4yyq4px.ap-northeast-2.rds.amazonaws.com:3306/aws2020
spring.datasource.username=admin
spring.datasource.password=tkdaud2020!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.datasource.hikari.maximum-pool-size= 5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.main.allow-circular-references=true
logging.level.org.springframework.security=DEBUG

# api
server.port=8080 
server.error.whitelabel.enabled=false
#Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api/api-docs
#JSON
server.error.include-message=always
server.error.include-binding-errors=always
